/*
 * This Java source file was generated by the Gradle 'init' task.
 */
class App {
    val greeting: String
        get() = "Hello world."

    companion object {

        // TODO: How to declare a top-level main with kotlin?
        @JvmStatic
        fun main(args: Array<String>) {
            println(App().greeting)
        }
    }
}
